name: FoD issues to GitHub (API)

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: fortify/gha-fod-generate-sarif@master
        with:
          base-url: ${{ secrets.FOD_EIGHTBALL_BASE_URL }}
          tenant: ${{ secrets.FOD_EIGHTBALL_TENANT }}
          user: ${{ secrets.FOD_EIGHTBALL_USER }}
          password: ${{ secrets.FOD_EIGHTBALL_PAT }}
          release-id: ${{ secrets.FOD_EIGHTBALL_RELEASE_ID }}
          output: ./sarif/output.sarif
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ./sarif/output.sarif
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: sarif-files
          path: ./sarif
